/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CDC;

import Business.Ecosystem;
import Business.Network.Network;
import Business.Vaccine.Vaccine;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vinay Limbare
 */
public class ManageVaccinesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageVaccinesJPanel
     */
    private JPanel userProcessContainer;
    private Ecosystem system;
    private static int count = 0;

    public ManageVaccinesJPanel(JPanel userProcessContainer, Ecosystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        populateVaccineJTable();

    }

    public void populateVaccineJTable() {
        DefaultTableModel model = (DefaultTableModel) vaccineJTable.getModel();

        model.setRowCount(0);
        for (Vaccine vaccine : system.getVaccineDirectory().getVaccineList()) {
            Object[] row = new Object[2];
            row[0] = vaccine.getVaccineId();
            row[1] = vaccine;
            model.addRow(row);
        }
    }

    public void populateVaccineJTable(int vaccId) {
        DefaultTableModel model = (DefaultTableModel) vaccineJTable.getModel();

        model.setRowCount(0);
        for (Vaccine vaccine : system.getVaccineDirectory().getVaccineList()) {
            if (vaccine.getVaccineId() == vaccId) {
                Object[] row = new Object[2];
                row[0] = vaccine.getVaccineId();
                row[1] = vaccine;
                model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        vaccineJTable = new javax.swing.JTable();
        backJButton = new javax.swing.JButton();
        refreshJButton = new javax.swing.JButton();
        requestJButton = new javax.swing.JButton();
        deleteJButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        vccIdJTextField = new javax.swing.JTextField();
        searchJButton = new javax.swing.JButton();
        vaccineNameJTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        diseaseJTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        priceJTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        manuDateJTextField = new javax.swing.JTextField();
        expDateJTextField = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Manage Vaccines");

        vaccineJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(vaccineJTable);

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        refreshJButton.setText("Refresh");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });

        requestJButton.setText("Add Vaccine");
        requestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestJButtonActionPerformed(evt);
            }
        });

        deleteJButton.setText("Delete Vaccine");
        deleteJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteJButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Search Vaccine");

        jLabel5.setText("Enter Product ID :");

        vccIdJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vccIdJTextFieldActionPerformed(evt);
            }
        });

        searchJButton.setText("Search");
        searchJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchJButtonActionPerformed(evt);
            }
        });

        vaccineNameJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaccineNameJTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Name :");

        jLabel3.setText("Disease");

        diseaseJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diseaseJTextFieldActionPerformed(evt);
            }
        });

        jLabel6.setText("Price");

        priceJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceJTextFieldActionPerformed(evt);
            }
        });

        jLabel7.setText("Manufacture Date");

        jLabel8.setText("Expire Date");

        expDateJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expDateJTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(diseaseJTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vaccineNameJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(priceJTextField)
                            .addComponent(manuDateJTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(expDateJTextField)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(vccIdJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(searchJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(88, 88, 88)
                                        .addComponent(jLabel4))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backJButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(refreshJButton))
                            .addComponent(deleteJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(requestJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(backJButton)
                            .addComponent(refreshJButton))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(jLabel4)
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(vccIdJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(searchJButton))))
                        .addGap(38, 38, 38)
                        .addComponent(deleteJButton)
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vaccineNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(diseaseJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(priceJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(jLabel7))
                    .addComponent(manuDateJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(expDateJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(requestJButton)
                .addContainerGap(75, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        // TODO add your handling code here:
        populateVaccineJTable();
    }//GEN-LAST:event_refreshJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void requestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestJButtonActionPerformed
        // TODO add your handling code here:
        int tempId = 1;
        for (Vaccine vaccine : system.getVaccineDirectory().getVaccineList()) {
            if (tempId == vaccine.getVaccineId()) {
                tempId++;
            }
        }

        if(vaccineNameJTextField.getText().isEmpty() || diseaseJTextField.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Field(s) cannot be empty !!!");
            return;
        }
        Vaccine vaccine = system.getVaccineDirectory().addVaccine(tempId, vaccineNameJTextField.getText(), diseaseJTextField.getText(), 0, null, null);
        try{
        vaccine.setVaccinePrice(Float.parseFloat( priceJTextField.getText()));
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Enter only digits");
            return;
        }
        for (Network network : system.getNetworkDirectory().getNetworkList()) {
            network.getInventoryDirectory().addInventory(network, vaccine, 0);
        }
        vaccine.setManufactureDate(manuDateJTextField.getText());
        vaccine.setExpiryDate(expDateJTextField.getText());
        JOptionPane.showMessageDialog(null, "Vaccine is added!!!");
        populateVaccineJTable();
    }//GEN-LAST:event_requestJButtonActionPerformed

    private void deleteJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = vaccineJTable.getSelectedRow();
        
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row !!!");
            return;
        }

        Vaccine vaccine = (Vaccine) vaccineJTable.getValueAt(selectedRow, 1);
        system.getVaccineDirectory().removeVaccine(vaccine);
        JOptionPane.showMessageDialog(null, "Removed");
        populateVaccineJTable();

    }//GEN-LAST:event_deleteJButtonActionPerformed

    private void vccIdJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vccIdJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vccIdJTextFieldActionPerformed

    private void vaccineNameJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaccineNameJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vaccineNameJTextFieldActionPerformed

    private void diseaseJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diseaseJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diseaseJTextFieldActionPerformed

    private void searchJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchJButtonActionPerformed
        // TODO add your handling code here:
        if(vccIdJTextField.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Enter an ID to search !!!");
            return;
        }
        populateVaccineJTable(Integer.parseInt(vccIdJTextField.getText()));
    }//GEN-LAST:event_searchJButtonActionPerformed

    private void priceJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceJTextFieldActionPerformed

    private void expDateJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expDateJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expDateJTextFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton deleteJButton;
    private javax.swing.JTextField diseaseJTextField;
    private javax.swing.JTextField expDateJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField manuDateJTextField;
    private javax.swing.JTextField priceJTextField;
    private javax.swing.JButton refreshJButton;
    private javax.swing.JButton requestJButton;
    private javax.swing.JButton searchJButton;
    private javax.swing.JTable vaccineJTable;
    private javax.swing.JTextField vaccineNameJTextField;
    private javax.swing.JTextField vccIdJTextField;
    // End of variables declaration//GEN-END:variables
}
