/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.NationalDistributor;

import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Vinay Limbare
 */
public class NationalDistributorAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DistributorAdminWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private Ecosystem system;

    public NationalDistributorAdminWorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount, Enterprise enterprise, Ecosystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.system = system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        approveOrdersButton = new javax.swing.JButton();
        manageFinanceJButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("National Distributor Admin Work Area");

        approveOrdersButton.setText("Manage Orders");
        approveOrdersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveOrdersButtonActionPerformed(evt);
            }
        });

        manageFinanceJButton.setText("Manage Finance");
        manageFinanceJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageFinanceJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jLabel1)
                .addGap(168, 168, 168))
            .addGroup(layout.createSequentialGroup()
                .addGap(296, 296, 296)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(approveOrdersButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageFinanceJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel1)
                .addGap(62, 62, 62)
                .addComponent(approveOrdersButton)
                .addGap(47, 47, 47)
                .addComponent(manageFinanceJButton)
                .addContainerGap(168, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void approveOrdersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveOrdersButtonActionPerformed
        ManageOrdersJPanel manageOrdersJPanel = new ManageOrdersJPanel(userProcessContainer, userAccount, enterprise, system);
        userProcessContainer.add("ApproveCdcOrdersJPanel", manageOrdersJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_approveOrdersButtonActionPerformed

    private void manageFinanceJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageFinanceJButtonActionPerformed
        // TODO add your handling code here:
        ManageNDFinanceJPanel manageNDFinanceJPanel = new ManageNDFinanceJPanel(userProcessContainer, userAccount, enterprise, system);
        userProcessContainer.add("ApproveCdcOrdersJPanel", manageNDFinanceJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageFinanceJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton approveOrdersButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageFinanceJButton;
    // End of variables declaration//GEN-END:variables
}
