/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Hospital.OrderRole;

import javax.swing.JPanel;
import Business.Order.OrderItem;
import java.awt.CardLayout;

/**
 *
 * @author Vinay Limbare
 */
public class ViewOrderItemDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewOrderItemDetailsJPanel
     */
    private JPanel userProcessConatiner;
    private OrderItem orderItem;

    public ViewOrderItemDetailsJPanel(JPanel userProcessContainer, OrderItem orderItem) {
        initComponents();
        this.userProcessConatiner = userProcessContainer;
        this.orderItem = orderItem;
        populateFields();
    }

    private void populateFields() {
        productNameText.setText(orderItem.getVaccine().getVaccineName());
        productQuantityText.setText(String.valueOf(orderItem.getQuantity()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        productNameLabel = new javax.swing.JLabel();
        productQuantityLabel = new javax.swing.JLabel();
        productNameText = new javax.swing.JTextField();
        productQuantityText = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        productNameLabel.setText("Vaccine Name");
        add(productNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        productQuantityLabel.setText("Vaccine Quantity");
        add(productQuantityLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, -1));

        productNameText.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        productNameText.setEnabled(false);
        add(productNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 120, -1));

        productQuantityText.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        productQuantityText.setEnabled(false);
        add(productQuantityText, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 120, -1));

        backButton.setText("<<  Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("View Order Details Page");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        userProcessConatiner.remove(this);
        CardLayout layout = (CardLayout) userProcessConatiner.getLayout();
        layout.previous(userProcessConatiner);
    }//GEN-LAST:event_backButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel productNameLabel;
    private javax.swing.JTextField productNameText;
    private javax.swing.JLabel productQuantityLabel;
    private javax.swing.JTextField productQuantityText;
    // End of variables declaration//GEN-END:variables
}
