/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.StatePHD;

import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Enterprise.PharmacyEnterprise;
import Business.Network.Network;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.ProviderRegistrationWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.JobAttributes;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vinay Limbare
 */
public class RegistrationRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegistrationRequestJPanel
     */
    JPanel userProcessContainer;
    UserAccount account;
    Enterprise enterprise;
    Ecosystem system;

    public RegistrationRequestJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, Ecosystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.enterprise = enterprise;
        this.system = system;

        populateTable();
    }

    private void populateTable() {

        DefaultTableModel dtm = (DefaultTableModel) registrationRequestJTable.getModel();
        dtm.setRowCount(0);

        for (WorkRequest workRequest : enterprise.getWorkQueue().getWorkRequestList()) {
            if (workRequest instanceof ProviderRegistrationWorkRequest) {
                ProviderRegistrationWorkRequest wrk = (ProviderRegistrationWorkRequest) workRequest;
                Object[] row = new Object[4];
                row[0] = workRequest.getSender().getUsername();
                row[1] = workRequest;
                row[2] = workRequest.getReceiver();
                row[3] = wrk.getProviderType();
                dtm.addRow(row);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        registrationRequestJTable = new javax.swing.JTable();
        assignJButton = new javax.swing.JButton();
        approveJButton = new javax.swing.JButton();
        rejectJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        backJButton1.setText("<< Back");
        backJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton1ActionPerformed(evt);
            }
        });

        registrationRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Provider Name", "Status", "Assigned to", "Provider Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(registrationRequestJTable);

        assignJButton.setText("Assign to me");
        assignJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignJButtonActionPerformed(evt);
            }
        });

        approveJButton.setText("Approve");
        approveJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveJButtonActionPerformed(evt);
            }
        });

        rejectJButton.setText("Reject");
        rejectJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejectJButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Provider Registration");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backJButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(assignJButton)
                                .addGap(132, 132, 132)
                                .addComponent(approveJButton)
                                .addGap(132, 132, 132)
                                .addComponent(rejectJButton))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(jLabel1)))
                .addContainerGap(197, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backJButton1)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assignJButton)
                    .addComponent(approveJButton)
                    .addComponent(rejectJButton))
                .addContainerGap(164, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButton1ActionPerformed

    private void assignJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = registrationRequestJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row !!!");
            return;
        }

        if (registrationRequestJTable.getValueAt(selectedRow, 2) != null) {
            JOptionPane.showMessageDialog(null, "Already assigned !!!");
            return;
        }

        WorkRequest wrk = (WorkRequest) registrationRequestJTable.getValueAt(selectedRow, 1);

        wrk.setReceiver(account);
        populateTable();
    }//GEN-LAST:event_assignJButtonActionPerformed

    private void approveJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = registrationRequestJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row !!!");
            return;
        }
        if (registrationRequestJTable.getValueAt(selectedRow, 1).equals("Approved")) {
            JOptionPane.showMessageDialog(null, "Already Approved !!!");
            return;

        }
        WorkRequest wrk = (WorkRequest) registrationRequestJTable.getValueAt(selectedRow, 1);
        wrk.setStatus("Approved");

        UserAccount user = wrk.getSender();

        Network n = null;
        for (Network network : system.getNetworkDirectory().getNetworkList()) {
            for (Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (e == enterprise) {
                    n = network;
                    break;
                }
            }
        }
        HospitalEnterprise e1 = null;
        PharmacyEnterprise e2 = null;
        for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
            if (e instanceof HospitalEnterprise) {
                for (UserAccount us : e.getUserAccountDirectory().getUserAccountList()) {
                    if (user.getUsername().equals(us.getUsername())) {
                        e1 = (HospitalEnterprise) e;
                    }
                }

            }
            if (e instanceof PharmacyEnterprise) {
                for (UserAccount us : e.getUserAccountDirectory().getUserAccountList()) {
                    if (user.getUsername().equals(us.getUsername())) {
                        e2 = (PharmacyEnterprise) e;
                    }
                }

            }
        }
        if (e1 != null) {
            e1.setRegistrationStatus("Approved");
        }
        if (e2 != null) {
            e2.setRegistrationStatus("Approved");
        }
        populateTable();
    }//GEN-LAST:event_approveJButtonActionPerformed

    private void rejectJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejectJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = registrationRequestJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row !!!");
            return;
        }
        if (registrationRequestJTable.getValueAt(selectedRow, 1).equals("Rejected")) {
            JOptionPane.showMessageDialog(null, "Already Approved !!!");
            return;

        }
        

        Network n = null;
        WorkRequest wrk = (WorkRequest) registrationRequestJTable.getValueAt(selectedRow, 1);
        UserAccount user = wrk.getSender();
        wrk.setStatus("Rejected");
        JOptionPane.showMessageDialog(null, "Rejected the request");
        HospitalEnterprise e1 = null;
        PharmacyEnterprise e2 = null;
        for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
            if (e instanceof HospitalEnterprise) {
                for (UserAccount us : e.getUserAccountDirectory().getUserAccountList()) {
                    if (user.getUsername().equals(us.getUsername())) {
                        e1 = (HospitalEnterprise) e;
                    }
                }

            }
            if (e instanceof PharmacyEnterprise) {
                for (UserAccount us : e.getUserAccountDirectory().getUserAccountList()) {
                    if (user.getUsername().equals(us.getUsername())) {
                        e2 = (PharmacyEnterprise) e;
                    }
                }

            }
        }
        if (e1 != null) {
            e1.setRegistrationStatus("Rejected");
        }
        if (e2 != null) {
            e2.setRegistrationStatus("Rejected");
        }
        populateTable();
    }//GEN-LAST:event_rejectJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton approveJButton;
    private javax.swing.JButton assignJButton;
    private javax.swing.JButton backJButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable registrationRequestJTable;
    private javax.swing.JButton rejectJButton;
    // End of variables declaration//GEN-END:variables
}
